services:
  reverse-proxy:
    image: traefik:v3.2
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  server:
    depends_on:
      - rabbitmq
      - db
    build:
      context: server
    labels:
      traefik.http.routers.server.rule: PathPrefix(`/api`)
      traefik.http.services.server.loadbalancer.server.port: 5000
      traefik.http.middlewares.strip-api.stripprefix.prefixes: /api
      traefik.http.routers.server.middlewares: strip-api@docker

  web-client:
    depends_on:
      - server
    build:
      context: client/web
    labels:
      traefik.http.routers.web-client.rule: PathPrefix(`/`)
      traefik.http.services.web-client.loadbalancer.server.port: 3000

  db:
    image: postgres:17.1
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:4.0
