services:
  reverse-proxy:
    command:
      - --providers.docker=true
      - --api.insecure=true
      - --log.level=DEBUG
    ports:
      - "8080:8080"

  server:
    build:
      target: dev
    environment:
      NODE_ENV: development
    develop:
      watch:
        - path: server
          action: sync
          target: /usr/src/app/
        - path: server/package.json
          action: rebuild

  web-client:
    build:
      target: dev
    develop:
      watch:
        - path: client/web
          action: sync
          target: /app
        - path: client/web/package.json
          action: rebuild

  pgadmin4:
    image: dpage/pgadmin4:8.13
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    labels:
      traefik.http.routers.pgadmin4.rule: Host(`pgadmin4.localhost`)

  db:
    volumes:
      - db-dev-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.0-management
    labels:
      traefik.http.routers.rabbitmq.rule: Host(`rabbitmq.localhost`)
      traefik.http.services.rabbitmq.loadbalancer.server.port: 15672

volumes:
  db-dev-data:
